name: "default"

on:
  push:
    branches:
      - main
      - dev

env:
  # Container Registry
  CONTAINER_REGISTRY_HOSTNAME: ghcr.io
  CONTAINER_REGISTRY_USERNAME: Sydnod Operations
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.__SYDNODOPS_GITHUB_ACCESS_TOKEN }}
  CONTAINER_REGISTRY_REPOSITORY: sydnod
  CONTAINER_REGISTRY_IMAGE_NAME: postgres-backup-azure-storage

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      # Checkout source code
      - name: Checkout source code
        uses: actions/checkout@v3

      # Setup Docker using buildx-action
      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      # Login to Docker Container Registry
      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY_HOSTNAME }}
          username: ${{ env.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ env.CONTAINER_REGISTRY_PASSWORD }}

      # Build Docker image with a :latest and :<git sha> tag
      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile
          #build-args: |
          tags: |
            ${{ env.CONTAINER_REGISTRY_HOSTNAME }}/${{ env.CONTAINER_REGISTRY_REPOSITORY }}/${{ env.CONTAINER_REGISTRY_IMAGE_NAME }}:latest
            ${{ env.CONTAINER_REGISTRY_HOSTNAME }}/${{ env.CONTAINER_REGISTRY_REPOSITORY }}/${{ env.CONTAINER_REGISTRY_IMAGE_NAME }}:${{ github.sha }}
